### PR TITLE
Update config with new blocks & items from MC 1.16

### PR DESCRIPTION
**Pull request by Yldales**
Hi,

#### Description: 

This PR attempt to update the following Towny's configuration nodes with blocks and items added in MC 1.16:
- new_world_settings.plot_management.block_delete.**unclaim_delete**
- new_world_settings.plot_management.mayor_plotblock_delete.**mayor_plot_delete**
- new_world_settings.plot_management.revert_on_unclaim.**block_ignore**
- protection.**item_use_ids**
- protection.**switch_ids**
- _TBD: global_town_settings.**farm_plot_allow_blocks**_
- _TBD: unclaimed.**unclaimed_zone_ignore**_
- _TBD: war.event.**allow_block_griefing**_
- _TBD: war.warzone.**explosions_ignore_list**_

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [ ] I have tested this pull request for defects on a server (**Will do.**)

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Thanks for this, your IDE has reformatted the spacing on the config so it considers it a complete re-write. Can you fix the spacing changes?

**Comment by Yldales** [comment]
Oops. Yes. I'll (try to) fix that.

**Comment by LlmDl** [comment]
I'm afraid that still didn't quite get it. We use 4 spaces. Your IDE formatted the entire class. If you want to try again you can, or let me know if you'd like me to take care of it.

**Comment by suneettipirneni** [comment]
This one is borked use #4126 instead.

**Pull request closed without merging**
