### PR TITLE
Backport: 0.96.0.0 for 1.13.2

### PR DESCRIPTION
**Pull request by TheFlagCourier**
#### Description: 

Backports the master branch to 1.13.2 for the 0.96.0.0 Release (Tentative). This should probably be the *last* 1.13 backport, barring any hot-fixes. Further modifications to Towny should not be held back for the sake of 1.13 backports, and working around API removals (as noted in next section) is not ideal.

Merge should not happen until:
- Proper sanity checks from 1.13 admins are received
- A 0.96.0.0 tag is assigned on the Master branch.
Further changes to master will be cherry-picked in, if required.

____
#### New Nodes/Commands/ConfigOptions: 

N/A - This is a backport to Spigot-API 1.13.2. Only changes made are for compatibility's sake. 
> The ProtectionRegenTask class from the 1.13 branch was used over the master branch's copy. This is due to BlockInventoryHolder not existing in the Spigot 1.13.2 API. This more than likely will cause issues, but it builds fine. A necessary fix can be made if required.

____
#### Relevant Towny Issue ticket:

N/A - No relevant issue ticket is open at this time.

____
- [ ] I have tested this pull request for defects on a server. 

  :x:  I do not run 1.13.x myself - though the following build ([Towny-0.96.0.0-1.13.2-Alpha_8.jar](https://cdn.discordapp.com/attachments/648719063417225216/684168257766293601/Towny-0.96.0.0-1.13.2-Alpha_8.jar)) is available for those who wish to test and confirm for themselves.

____
#### Other Notes:
- This release requires testing with the recommended TownyChat (and TownyNameUpdater) for 0.96.0.0 (ie: latest)
- Regeneration Tasks **may** fail - I am not well associated with the methods that call the ProtectionRegenTask, so I cannot confirm or deny it's sanity.
____

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by suneettipirneni** [comment]
Yeah screw regen for 1.13, it's way too much work without the generified `InventoryHolder`

**Comment by galacticwarrior9** [comment]
Currently using the latest build from Discord on a production server with 30-80 players - no obvious issues have been encountered so far.

**Comment by TheFlagCourier** [comment]
@galacticwarrior9 Good to hear - Alpha 5 was just pushed here (see main post) and on the Discord.

**Comment by GhaziShah** [comment]
Claimed townblocks are sometimes randomly unclaimed after restarts. I haven't found a way to consistently reproduce this, the chance of it occurring is higher the more towns you have (I have 100+ on my server). It seems to occur after server restarts when using flatfile. I'm sorry this can't be more informative, but I'm hard-pressed for details. Is this already a known issue, or should I file a bug report

**Comment by LlmDl** [comment]
> Claimed townblocks are sometimes randomly unclaimed after restarts. I haven't found a way to consistently reproduce this, the chance of it occurring is higher the more towns you have (I have 100+ on my server). It seems to occur after server restarts when using flatfile. I'm sorry this can't be more informative, but I'm hard-pressed for details. Is this already a known issue, or should I file a bug report

It is an issue we have begun to see fairly rarely. Only one ticket has been filed as of today for it.

**Pull request merged**
