### PR TITLE
Let plugins access to original lines via StatusScreenEvent

### PR DESCRIPTION
**Pull request by LudwigHornslied**
#### Description: 

I'm making a Towny Add-On plugin called "TownyKOTH" and I wanna show simplified town informations for specified towns but with current TownStatusScreenEvent I can't so made changes in API
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
While this is an interesting idea, it could be severely limiting for users if they cannot get the information that was removed.

It could also be used by another plugin maliciously. I'll defer to what the other team members think about this though.

**Comment by silverwolfg11** [comment]
I think have a method to allow plugins to access and modify the town status screen would be useful.
I don't think plugins would intentionally maliciously use it. But like for other things, I think it really falls on server administrators to make sure they don't have any malicious plugins and know what the plugins they installed are doing. 

That being said, I think this method of exposing the lines is actually bad in terms of API. Exposing those lines would lead to a lot of bad and unstable code if plugins tried to modify or access them. For one thing, that list varies based on the actual town information. 
A plugin trying to modify or access a specific line would most likely have to do it based on some string matching pattern which guarantees no consistency. For example, the message could change, and then that string pattern wouldn't work.
Furthermore, suppose a plugin tried to delete a line based on that string search. There may be other information within that line the plugin didn't intend to delete, but had no way of knowing that was there.

Overall, I'm in favor of the general idea, but I'm not in favor of just exposing the raw list for modification.

**Comment by 0xBit-MC** [comment]
> It'd be best if the friendly fire test event was moved into it's own PR, since they're 2 seperate things.

I agree with you on that.

**Comment by LlmDl** [comment]
There's a change coming to status screens which will probably make this something achievable. As I said in the discord, the friendlyfire thing should be a separate PR.

**Pull request closed without merging**
