### PR TITLE
Implemented New Plot Events

### PR DESCRIPTION
**Pull request by Kovalskki**
#### Description: 
Adds new plot events

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — CHANGES_REQUESTED** [review]
At first glance this looks good, however the the old plot events cannot be moved. The old events need to be deprecated with the new events added to the packages you've created.

**Comment by LlmDl** [comment]
Also, will you be re-submitting your jail events fix?

**Comment by Kovalskki** [comment]
> Also, will you be re-submitting your jail events fix?

I'm new on git. Why should I re-submitting it again?

**Comment by LlmDl** [comment]
> > Also, will you be re-submitting your jail events fix?
> 
> I'm new on git. Why should I re-submitting it again?

It was not accepted and merged, only approved.

**Comment by Kovalskki** [comment]
Its okey now?

**Comment by LlmDl** [comment]
It is an improvement, can you try to remove the PlotClearEvent from your PR? It doesn't look like there's any actual changes.

**Pull request closed without merging**
