### PR TITLE
Update language file es-419.yml

### PR DESCRIPTION
**Pull request by GNosii**
#### Description: 

Updates `es-419.yml`
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
There's a few more strings to add, and the file is conflicting now, might as well update it to 0.105.

**Comment by GNosii** [comment]
> There's a few more strings to add, and the file is conflicting now, might as well update it to 0.105.

I'll currently mark this as an draft until es-419 can be translatede & merged.

**Comment by GNosii** [comment]
Conflicts fixed.

**Comment by GNosii** [comment]
@LlmDl can you check this out?

**Review by TheFlagCourier — APPROVED** [review]

**Comment by TheFlagCourier** [comment]
> Seems like it messed up the blame view

Looks like you overwrote the file with Unix (Mac/Linux) style End-Of-Line characters. Unless it's going to be forced via a `.gitattributes` file, stuff like this is bound to happen every now and then.

Should be fixed, and good-to-go.

**Comment by LlmDl** [comment]
I've butchered this PR and my IDE wont see the remote branch for some reason so I'm using your lines for version .103 and onwards manually.

**Pull request closed without merging**
