### PR TITLE
1.13+1.14 Commits

### PR DESCRIPTION
**Pull request by creatorfromhell**

### CODE REVIEW

**Comment by graywolf336** [comment]
@creatorfromhell is your system not preserving the line endings and the encoding of the files? That is the primary cause for all of these files being treated as if you've wiped them and redone everything. Also, changing the indents from what they were to what you prefer (if it's any difference) can also cause this. As @LlmDl said in the previous pull request, having all of this makes it really hard to see exactly what has changed...

**Comment by LlmDl** [comment]
@creatorfromhell @graywolf336 is right. Your IDE is overriding things like ordering of imports as well as whitespace. If you can sort that out you won't be disturbing the github history/blame for each line of code.

**Comment by creatorfromhell** [comment]
Yeah we determined this already @graywolf336. Although github has a nifty feature to not display whitespace changes for this one

**Comment by LlmDl** [comment]
Even though it can be hidden, if I accept it, you'll be the sole author for all the files involved. I think I might cherry pick the ~80 lines out of this that is needed and w/e whitespace settings your IDE has that doesn't match the rest of the Towny code can be made better for the next PR.

**Comment by LlmDl** [comment]
Done this one manually. Thanks @creatorfromhell for putting in the work.

**Pull request closed without merging**
