### PR TITLE
Swedish lang support

### PR DESCRIPTION
**Pull request by OskyEdz**
#### Description: 
Swedish support coninuation

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Looks much better, are you planning to translate more in this Pull Request or will this be it for now?

**Comment by OskyEdz** [comment]
I'm in the zone now. I hope to keep going during this week. But I can keep the comits on my side until I have more to add.

**Comment by LlmDl** [comment]
Hello @OskyEdz just a heads up: translation is happening on crowdin now: https://crowdin.com/project/townyadvanced

**Comment by OskyEdz** [comment]
Perfect. That'll make it much easier on my part to continue. It was a bit if a hassel keeping up with files in my PC.

**Comment by LlmDl** [comment]
Yep, I've given you the ability to proof-read your own work there. Thank you for continuing.

**Comment by OskyEdz** [comment]
I know I have some inconsistency with some words. That will be much easier to spot with the Crowdin-tools.

**Pull request merged**
