### PR TITLE
Tracking PR for the facilitation of removing or migrating FlagWar [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by TheFlagCourier**
So...

I've been toying around with moving FlagWar to its own dependent plugin, say TownyAdvanced/FlagWar. If we want to nuke it from the main repository, this PR will do it. 

Please don't actually apply this pull request to nuke it. 😨 This PR is only for tracking necessary changes. As it gets rebased, we'll see where it will still have an effect on the codebase.

It marks relevant areas that need attention first in other areas of the code. These probably need supplemented in the API.

It also marks relevant translation keys in the English localization. I've confirmed these are used nowhere else in Towny, so they should be good to cut from all localizations should an independent FlagWar implement its own localization calls.

### CODE REVIEW

**Comment by Romvnly-Gaming** [comment]
merge

**Comment by LlmDl** [comment]
It would appear a few of the latest commits got sucked into this branch and appear in the diff.

**Comment by TheFlagCourier** [comment]
Yeah, that'd be due to re-basing off of master before pushing forward. It'll probably be prudent to do a fresh branch for this to keep things clean.

**Comment by TheFlagCourier** [comment]
Closing this PR in favor of branching off of `master` after #4920 is merged, with a cleaner removal process. Changes are stashed and ready to stage when needed.

**Pull request closed without merging**
