### PR TITLE
Refactor/id mappings

### PR DESCRIPTION
**Pull request by TheFlagCourier**
#### Description: 

Separates out IdMappings into a Maven dependency, rather than directly including it within the TownyAdvanced Repository.

Also expands the LICENSE.md file to include 3rd-party licenses.
____
#### New Nodes/Commands/ConfigOptions: 

N/A

____
#### Relevant Towny Issue ticket:

N/A

____
- [ ] I have tested this pull request for defects on a server.
  - Will have it tested before removing draft status.

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
It could be a bit tricky nowadays to get old plot-block-data that was pre-material and still used IDs, but there were some tweaks I had to make to the existing id-mappings that were originally provided in order to get things to work. Has any testing been done using snapshots made with the old plot-block-data schema?

**Comment by TheFlagCourier** [comment]
@LlmDl No testing has been performed _yet_ - hence being a draft PR and not 'ready for review'.

**Comment by LlmDl** [comment]
> @LlmDl No testing has been performed _yet_ - hence being a draft PR and not 'ready for review'.
> I plan to get testing out of the way sometime this coming week.

Sounds good. Just didn't want that part of it to be forgotten.

**Comment by TheFlagCourier** [comment]
Okay, I've let this sit for way too long, and clearly haven't had the time to go back over it. Closing so it's out of the way.

**Pull request closed without merging**
