### PR TITLE
Update lang file of ja_JP

### PR DESCRIPTION
**Pull request by graycat27**
#### Description: 
Update Japanese lang file.
- new translations
- fix color 6f3462fc2afb7974849e4ddd91bcbbf5822ed5d9
____
#### New Nodes/Commands/ConfigOptions: 
none
____
#### Relevant Towny Issue ticket:
none
____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Translations are made on our crowdin page: https://crowdin.com/project/townyadvanced

You'll have to make your edits there.

**Comment by graycat27** [comment]
thanks for notice about crowdin page @LlmDl . I edited on there.  
By the way, some fixes may not be done with crowdin.  
```diff
+ L3 language name
+ L1601～1605 color replace syntax
```
may I make another PR about these?

**Comment by Warriorrrr** [comment]
The language name is unused so that one doesn't really matter

**Comment by LlmDl** [comment]
I will edit the incorrect colour tags, they have since been hidden because they should not have been translatable.

**Pull request closed without merging**
