### PR TITLE
Added the ability to sort with alternate comparators.

### PR DESCRIPTION
**Pull request by professorg**
Alternate comparators use "by" keyword in `/t list` and `/n list`.
Example: `/t list by name` sorts towns by name.

Partially implements #3174 
Added comparators:
- by name (town, nation)
- by residents (town, nation)
- by balance (town, nation)
- by towns (nation)

Tested on a basic level with a local server.
Only English translations included for new error messages.

### CODE REVIEW

**Comment by professorg** [comment]
Let me know if there's anything that needs changing, or if this is an undesirable feature. It errors with additional arguments, now, rather than ignoring all but the page number. I didn't include any modified help  information for the two affected commands.

**Comment by LlmDl** [comment]
I'll try to get this looked after when I can but it could be a little while. Thanks for the PR!

**Comment by LlmDl** [comment]
@professorg I've borked this up real good resolving the conflicts using their web-editor.
It has changed the whitespace for the entire TownCommand and NationCommand. If you could resubmit the PR without the conflicts I'll accept it ASAP.

**Comment by professorg** [comment]
@LlmDl I see what you mean. Working on it right now.

**Comment by professorg** [comment]
@LlmDl Hopefully fixed. Thank you for your patience.

**Comment by LlmDl** [comment]
I did a bit of translating, and moved your new strings down to the bottom of the file. Also had to enable the sorting by name for nations, which wasn't being used. Otherwise very nice. Thanks for your contribution!

**Pull request merged**
