### PR TITLE
Parse baltops asynchronously

### PR DESCRIPTION
**Pull request by Gamer153**
#### Description: 

Parse the baltops for nations and towns and display them asynchronously, it otherwise causes huge lagspikes in large servers.

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by Warriorrrr — COMMENTED** [review]
Instead of using BukkitRunnables, I'd recommend just using
```java
Bukkit.getScheduler().runTaskAsynchronously(plugin, () -> {
    //code here
});
```

**Comment by LlmDl** [comment]
Those commands aren't touching the economy plugin, (which is usually where the lag comes from,) they're only asking Towny's cached balances for values. Is it just the sorting causing the lag?

**Comment by Warriorrrr** [comment]
The sorting/formatting is where I'd imagine most of the lag comes from, especially since players could spam the command repeatedly.

**Review by LlmDl — APPROVED** [review]

**Comment by LlmDl** [comment]
Not sure how I missed this, the sorting is being done on the actual player balances instead of their cached balances, which is doing to cause lag. I'll fix that after this is merged.

**Pull request merged**
