### PR TITLE
Added Town rank related events

### PR DESCRIPTION
**Pull request by Artuto**
This would close issue #3041 if merged.

### CODE REVIEW

**Comment by Artuto** [comment]
Any update on this?

**Comment by LlmDl** [comment]
> Any update on this?

It will get added, just been busy.

**Comment by Apfel** [comment]
This looks pretty interesting, will this see any new activity?

**Comment by Artuto** [comment]
😐

**Comment by LlmDl** [comment]
Still being quite busy, on the plus side I have a newborn son which is pretty cool.

**Comment by graywolf336** [comment]
I know I'm late to the party, but congrats on the newborn!! 🎉

**Pull request merged**
