### PR TITLE
Ensure Objects are properly assigned, closed, and compared to improve safety and accuracy.

### PR DESCRIPTION
**Pull request by TheFlagCourier**
#### Description: 

The following commit contains changes that ensure the code executes as expected.
- Increase precision of mathematic functions by casting.
- Compare content of strings / objects, rather than locations in memory.
- Improve safety of closing Statements.
- Ensure the value of a variable is actually being assigned.
____
#### New Nodes/Commands/ConfigOptions: 

N/A - All changes are internal

____
#### Relevant Towny Issue ticket:

A subset of #4481, again just trying to break it up into logical bits..

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — COMMENTED** [review]
Looks fairly good.

Since this touches the SQLsource I want this to at least get tested.

The other thing I'm not sure about is many of the things you're casting to a double are ints. Any reason for that?

ie:
```java
nextprice = Math.round(Math.pow(TownySettings.getClaimPriceIncreaseValue() , getTownBlocks().size() + (double)i) * TownySettings.getClaimPrice());
```
getTownBlocks().size() and i are both ints.

**Comment by TheFlagCourier** [comment]
> Since this touches the SQLsource I want this to at least get tested.

Fair. I don't have access to a server running with SQL at the moment, so I may have to ask for help there.

> ...many of the things you're casting to a double are ints. Any reason for that?

Yeah, when math is performed on integers, the result will always be an integer. So things like memoryPercentage (a double) would report as an integer value. By casting an integer to a long or double, this increases precision. As a result of the cast, the other operand is automatically promoted to double, and java will handle it accordingly.

This actually goes into it in pretty good detail. https://wiki.sei.cmu.edu/confluence/display/java/NUM50-J.+Convert+integers+to+floating+point+for+floating-point+operations

**Comment by LlmDl** [comment]
> > Since this touches the SQLsource I want this to at least get tested.
> 
> Fair. I don't have access to a server running with SQL at the moment, so I may have to ask for help there.
> 
> > ...many of the things you're casting to a double are ints. Any reason for that?
> 
> Yeah, when math is performed on integers, the result will always be an integer. So things like memoryPercentage (a double) would report as an integer value. By casting an integer to a long or double, this increases precision. As a result of the cast, the other operand is automatically promoted to double, and java will handle it accordingly.
> 
> As an example:
> 
> ```
> int sum = 30;  
> double avg = sum / 4;
> ```
> 
> Would return 7, not 7.5.
> 
> This actually goes into it in pretty good detail. https://wiki.sei.cmu.edu/confluence/display/java/NUM50-J.+Convert+integers+to+floating+point+for+floating-point+operations

Sounds good. If need be, I'll do the sql test.

**Review by LlmDl — APPROVED** [review]
No problems on the mysql front.

**Pull request merged**
