### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by DayBreak365**

### CODE REVIEW

**Comment by LlmDl** [comment]
Let me know when you've finished.

**Comment by DayBreak365** [comment]
I think I've finished all. I'll send the Pull Request later if there's any problem.

**Comment by LlmDl** [comment]
Ok, I didn't count the lines, I just noticed that the end of the file doesn't have the same strings at the end of the rest of the files. Maybe you put them into a new order?

**Comment by DayBreak365** [comment]
I think the blank lines disappeared in the process of matching English and Korean files. The order seems the same. I will add blank lines in the file if it's necessary.

**Comment by LlmDl** [comment]
No blank lines are necessary, you are missing a few lines I added yesterday though:

```
msg_error_ta_plot_claim: 'Missing playername, ex: /ta plot claim PlayerNameHere'
msg_error_no_player_with_that_name: 'No player found with name %s'
msg_admin_has_given_you_a_plot: 'An admin has claimed a plot for you at: %s' 
```

**Comment by DayBreak365** [comment]
Added 😄

**Pull request merged**
