### PR TITLE
Add clickable text to confirmations messages.

### PR DESCRIPTION
**Pull request by suneettipirneni**
#### Description: 

Adds the ability to click the accept/cancel text on confirmation messages. Lang changes have been included.

The hover component can be seen in this picture:
Screen Shot 2020-01-08 at 10 31 50 PM
#### Relevant Towny Issue ticket:

#3534 
____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by suneettipirneni** [comment]
Well this comes down to UX problem now, should we still advertise the command or make it seem as though clicking is the only valid option, I understand the latter actually

**Comment by LlmDl** [comment]
Good point, we have a lot of space on each line what about "    Click this message to Confirm, or use /confirm"

**Comment by suneettipirneni** [comment]
Here's what is looks like now:
Screen Shot 2020-01-09 at 2 42 15 PM

**Comment by LlmDl** [comment]
So is this being applied to all confirmations?

**Comment by suneettipirneni** [comment]
Yeah, it’s using the confirmation function.

**Comment by suneettipirneni** [comment]
Updated pic:
Screen Shot 2020-01-10 at 2 16 22 PM

Also latest jar included

[Towny-0.95.2.7.jar.zip](https://github.com/TownyAdvanced/Towny/files/4048176/Towny-0.95.2.7.jar.zip)

**Comment by LlmDl** [comment]
I think the only thing that needs to be done is removing the green colouring from the message after the 
Capture
so [deny Ricktown] in green, rest of the line in white. So that if/when it goes to a new line it doesn't change from green to white. Otherwise it's working perfect.

**Comment by suneettipirneni** [comment]
Trailing text after the main clickable has been set to white:

Screen Shot 2020-01-12 at 9 40 01 PM

Updated jar:

**[Towny-0.95.2.7.jar 2.zip](https://github.com/TownyAdvanced/Towny/files/4051940/Towny-0.95.2.7.jar.2.zip)**

**Pull request merged**
