### PR TITLE
Update french.yml

### PR DESCRIPTION
**Pull request by Mitsu13Ion**
Update and corrected some line in french language

#### Description: 

It's only a update for the french language
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Will you be adding more commits or should I accept this today?

**Comment by Mitsu13Ion** [comment]
You can accept today, Thanks u

**Comment by LlmDl** [comment]
Ok, just let me know when you're done.

**Comment by Mitsu13Ion** [comment]
> 
> 
> Ok, just let me know when you're done.

You can accept ^^

**Pull request merged**
