### PR TITLE
Update spanish.yml

### PR DESCRIPTION
**Pull request by ElMoha943**
#### Description: translation up to 114 + some minor fixes in some war related messages.

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
This one has a conflict that has to be sorted out, as there has been a new line added. You should be able to rebase your branch and get the conflict resolved. If not, I can probably do it for you.

**Comment by ElMoha943** [comment]
fixed the issue and bumped to 0.115

**Comment by LlmDl** [comment]
Hello @ElMoha943 just a heads up: translation is happening on crowdin now: https://crowdin.com/project/townyadvanced

**Comment by ElMoha943** [comment]
> Hello @ElMoha943 just a heads up: translation is happening on crowdin now: https://crowdin.com/project/townyadvanced

Hi thanx for the heads up, i will take a look at it but never used it before.

**Pull request merged**
