### PR TITLE
Add PR Auto-Labeler back

### PR DESCRIPTION
**Pull request by suneettipirneni**
#### Description: 

We previously removed the auto-labeler GitHub workflow because it failed to run when forks we're requesting to PR. This has since been fixed and it now seems to be working as intended.

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
The labels should probably be changed to use the labels we already have in place https://github.com/TownyAdvanced/Towny/labels : Label-War, Label-Chat, Label-API, etc.

**Comment by suneettipirneni** [comment]
> The labels should probably be changed to use the labels we already have in place https://github.com/TownyAdvanced/Towny/labels : Label-War, Label-Chat, Label-API, etc.

Can we rename the ones in place?. I mean why are they all prefixed with "Label". _It is a label_ and your you're labeling it with a "Label". That's label-ception. That's like prefixing all of Towny's java files with "Code": "CodeTown", "CodeNation", "CodeTownblock". We know it's code and we know a label is a label. Why do we need torture ourselves with a redundant and meaningless prefix?

**Comment by LlmDl** [comment]
> > The labels should probably be changed to use the labels we already have in place https://github.com/TownyAdvanced/Towny/labels : Label-War, Label-Chat, Label-API, etc.
> 
> Can we rename the ones in place? I mean why are they all prefixed with "Label". _It is a label_ and your you're labeling it with a "Label". That's label-ception. That's like prefixing all of Towny's java files with "Code": "CodeTown", "CodeNation", "CodeTownblock". We know it's code and we know a label is a label. Why do we need torture ourselves with a redundant and meaningless prefix?

The way it is now, I have 90% of the labels I use on a very frequent basis at the top of the list, ie: Bug, Complete, Enhancement, with the labels underneath them in alphabetical order. Don't worry about label-ception.

**Comment by suneettipirneni** [comment]
> The way it is now, I have 90% of the labels I use on a very frequent basis at the top of the list, ie: Bug, Complete, Enhancement, with the labels underneath them in alphabetical order.

Yes, that why I recommend renaming those labels. If you rename them you can keep everything currently indexed under them, and eliminate the “label” prefix. Hence a win-win

**Comment by LlmDl** [comment]
> > The way it is now, I have 90% of the labels I use on a very frequent basis at the top of the list, ie: Bug, Complete, Enhancement, with the labels underneath them in alphabetical order.
> 
> Yes, that why I recommend renaming those labels. If you rename them you can keep everything currently indexed under them, and eliminate the “label” prefix. Hence a win-win.
> https://docs.github.com/en/enterprise/2.13/user/articles/editing-a-label

If we rename them all to remove the Label- part, Chat ends up high on the list above enhancement, complete. The ones I use frequently end up scattered through-out. You can make the labels conform to the labels we've used for years.

**Comment by suneettipirneni** [comment]
> The ones I use frequently end up scattered through-out. You can make the labels conform to the labels we've used for years.

Huh? You realize you can sort labels by relevance/usage and GitHub will save your preferred sorting method.

**Comment by suneettipirneni** [comment]
Even if you do use the alphabetic sorting, it still doesn’t make sense looking at the usage of each label. The most used labels are enhancement and bug, those are automatically applied so no digging is required. The other top labels are labels that begin with “label-” and those are manually applied. Also because they start with label you have to dig around to find them. I.e most of the manually put labels you use frequently don’t benefit from an alphabetical sort anyways. 
00726845-95D0-489F-93EE-FAD650D901F4

**Comment by LlmDl** [comment]
The screenshot you're showing is not the UI for actually applying labels to tickets. Adjust your PR to comply with the labels Towny uses.

**Comment by suneettipirneni** [comment]
> The screenshot you're showing is not the UI for actually applying labels to tickets. Adjust your PR to comply with the labels Towny uses.

Did you not read my last comment? You don't take advantage of the alphabetic system anyways you're contradicting yourself now. Most of the manually applied labels are "label-x" labels, which as I stated before aren't in any particular order. If I comply with the towny format, it's more characters for the same outcome.

**Comment by LlmDl** [comment]
When I apply a label to a ticket there's a few at the top of the list I use often. Your PRs labels aren't used by Towny, and they will muck with the list I use frequently.

**Comment by suneettipirneni** [comment]
> When I apply a label to a ticket there's a few at the top of the list I use often.


You once again seem to be neglecting my argument. 3rd time is a charm, let's walk through my argument once more.

Firstly, let's look at the screenshot:

This is a list that sorts the labels by usage (Yes, I'm aware this doesn't show when you want to apply it to an issue)

image
**Appendix A: A Listing of issues by usage.**

I didn't send appendix A to show you how you ***should be using labels***, but rather to show you ***how you currently use labels***

Let's analyze the usage of labels shown in appendix A. The top 2 are `bug` and `enhancement` these labels don't pertain to this conversation *because they're automatically applied when the ticket is created*. We never add the bug label *manually* because it's part of the bug issue template this is the same for the `enhancement` label.

Now that we know that both `bug` and `enhancement` are automatically applied and don't concern this conversation, let's look at the other labels on the list. 

Screen Shot 2020-08-29 at 11 11 26 PM

**Appendix B: A continuation of the list from Appendix A** 

Alright we're moving down the list of most used labels, let's analyze this.

We can see a common pattern, the most used *manually* applied labels are in the format "label-x". This means that they don't benefit from alphabetic ordering system you have in place. For example if I have this label set:

- "Label-Foo"
- "Label-Bar"

And then this label set:
- "Foo"
- "Bar"

We can sort them alphabetically:

First Set sorted:
- "Label-Bar"
- "Label-Foo"

Second Set sorted:
- "Bar"
- "Foo"

As you can see from the above examples the extra `Label-` prefix does nothing as the result of ordering is essentially the same.

Now let's return to the main argument:

"My most *applied* labels are at the top of the alphabetically sorted list." - Llmdl

Let's prove this statement false by using a contradiction.

If you look a the alphabetically sorted list of labels this is the rankings:

1. bug
2. CI | CD
3. Completed
4. dependencies
5. duplicate
6. FlagWar
7.  enhancement

Now as I stated previously, `bug` and `enhancement` can be removed from the equation because they're automatically applied in all cases. So we end up with:

1. CI | CD
2. Completed
3. dependencies
4. duplicate
5. FlagWar

So according to the statement: "My most *applied* labels are at the top of the alphabetically sorted list." All of the things I listed above *must* be the most applied labels. However, that is far from the reality of how the labels are handled as shown by appendix C:

|  Usage Ranking  | What Llmdl States is the most used | What is actually the most used  |
|----|------------------------------------|---------------------------------|
| 1 | CI \| CD - 0 active Usages         | Label-Money - 16 active usages  |
| 2 |  Completed - 0 active Usages       | Label-War - 12 active usages    |
| 3 | dependencies - 0 active Usages     | Label-Towns - 12 active usages  |
| 4 | duplicate - 0 active Usages        | Label-Nations - 7 active usages |
| 5 | FlagWar - 4 active Usuages         | Label Chat - 7 active usages    |

**Appendix C: A table comparing usages based on alphabetic ordering vs actual usage.**

As trivially shown by the table above "Label-X" is more widely used than the label *you purposely don't prefix to leave on the top of the list*. 

I want you to understand that everything up to this point is based purely on statistics and devoid of any opinion.

Let me ask you a question:
"Does it make sense to put labels that are rarely used on the top?" - The answer is no. 

The alphabetic ordering offers no guidance on which labels are used most frequently. Thus adding the "Label-X" makes no positive impact. If we remove "Label-X" we still are going to get the same behavior, which means the only difference between "Label-X" and "X" is less typing.

**Comment by LlmDl** [comment]
Ok be a dink about it.

**Comment by suneettipirneni** [comment]
There a quite a few signs that someone shows when they're losing an argument. One of these signs you clearly exhibited. The one I'm referring to is called **Ad Hominem**. 

What is Ad Hominem: 
> Attacking the person making the argument, rather than the argument itself, when the attack on the person is completely irrelevant to the argument the person is making.

This is commonly used when someone has little-to-no logical ground to stand on. In fact, the current President of the US is one of the most common users of Ad Hominem.

 Why? Because he uses his position of power to shut people out he disagrees with regardless of the validity of their argument. And when this is done without a counter-argument it looks especially bad within the public eye.

**Comment by LlmDl** [comment]
I was referring to your behaviour in general on this ticket. Not something I'll tolerate. Go be a condescending prick somewhere else this morning.

**Comment by suneettipirneni** [comment]
I will stop being condescending when I don't have to keep reiterating the same facts repeatedly. 

How would you act if someone kept seemingly ignoring your comments? Oh yeah:image

Condescending right?

**Comment by LlmDl** [comment]
Somewhere else I said.

**Pull request closed without merging**
