### PR TITLE
Add color code translation to resident formatted names.

### PR DESCRIPTION
**Pull request by suneettipirneni**
#### Description: 

This fixes the formatted name for residents that have color codes in their username. For example &l&omy_username will now be translated properly to _**my_username**_ 

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Does this also handle the town and nation names with colour codes, seen in the /t and /n list outputs? Doesn't look like it.

**Comment by suneettipirneni** [comment]
> Does this also handle the town and nation names with colour codes, seen in the /t and /n list outputs? Doesn't look like it.

There’s no reason to because ampersands aren’t allowed in town and nation names

**Comment by LlmDl** [comment]
> There’s no reason to because ampersands aren’t allowed in town and nation names

They are though.

**Comment by LlmDl** [comment]
k

**Comment by LlmDl** [comment]
Realized I had a test config with the older regex, retested with new regex:

**Pull request merged**
