### PR TITLE
Add localization for the Flatfile data handler

### PR DESCRIPTION
**Pull request by TheFlagCourier**
#### Description: 

This PR adds localization strings for the TownyFlatFileSource class, allowing debug and error messages to be localized.

> As an asside, this also force converts all languages except English to CRLF file endings, in line with the .editorconfig. Right now, about half of our files are encoded with LF line endings... I recommend a one-time forced conversion, with the addition of a .gitattributes file and EditorConfig maven plugin. Manually ensuring files are improperly encoded to prevent large diffs is a pain in the butt.

____
#### New Nodes/Commands/ConfigOptions: 

New localization strings for the TownyFlatFileSource class.
```yaml
#Added in 0.99 - FlatFile L10N
flatfile_dbg_cannot_set_capital_try_next: 'Nation %s could not set capital to %s, selecting a new capital...'
flatfile_dbg_deleting_duplicate: 'Deleting: %s which is a duplicate of %s'
flatfile_dbg_folders_found: 'Folders found %s'
flatfile_dbg_group_file_missing_town_delete: 'Group file missing Town, deleting %s'
flatfile_dbg_loading_group_list: 'Loading Group list...'
flatfile_dbg_loading_nation: 'Loading Nation: %s'
flatfile_dbg_loading_nation_list: 'Loading Nation list...'
flatfile_dbg_loading_resident: 'Loading Resident: %s'
flatfile_dbg_loading_resident_list: 'Loading Resident list...'
flatfile_dbg_loading_server_world_list: 'Loading Server World List...'
flatfile_dbg_loading_town: 'Loading Town: %s'
flatfile_dbg_loading_town_list: 'Loading Town list...'
flatfile_dbg_loading_townblock_list: 'Loading TownBlock list...'
flatfile_dbg_loading_world: 'Loading World: %s'
flatfile_dbg_loading_world_list: 'Loading World List...'
flatfile_dbg_mismatched_townblock_size: '%s townblocks were found with a town_block_size that does not match your config, they were not loaded into memory.'
flatfile_dbg_missing_file_delete_group_entry: 'Missing file: %s deleting entry in group.txt'
flatfile_dbg_missing_file_delete_groups_entry: 'Missing file: %s deleting entry in groups.txt'
flatfile_dbg_removing_nation_not_found: 'Removing %s because they are not found in the nations.txt'
flatfile_dbg_removing_resident_not_found: 'Removing %s because they are not found in the residents.txt'
flatfile_dbg_removing_town_not_found: 'Removing %s because they are not found in the towns.txt.'
flatfile_dbg_town_fetch_outlaw: 'Town Fetching Outlaw: %s'
flatfile_dbg_undefined_capital_select_new: 'Nation %s did not have a capital defined, selecting a new capital...'
flatfile_dbg_world_loaded_townblocks: 'World: %s loaded %s TownBlocks.'
flatfile_err_cannot_create_defaults: 'Could not create flatfile default files and folders.'
flatfile_err_could_not_add_to_town: 'Could not add to town!'
flatfile_err_exception_reading_file: 'Loading Error: Exception while reading file %s'
flatfile_err_exception_reading_group_file_at_line: 'Loading Error: Exception while reading Group file %s at line: %s'
flatfile_err_exception_reading_townblock_file_at_line: 'Loading Error: Exception while reading TownBlock file %s at line: %s.'
flatfile_err_exception_reading_world_file_at_line: 'Loading Error: Exception while reading world file %s at line: %s, in towny/data/worlds/%s.txt'
flatfile_err_file_error_reading_world_file_at_line: 'Loading Error: File error while reading %s at line: %s, in towny/data/worlds/%s.txt'
flatfile_err_homeblock_load_invalid_location: '[Warning] %s - HomeBlock tried to load invalid Location.'
flatfile_err_homeblock_load_invalid_townblock: '[Warning] %s - HomeBlock tried to load invalid TownBlock.'
flatfile_err_homeblock_load_invalid_world: '[Warning] %s - HomeBlock tried to load invalid World.'
flatfile_err_invalid_townblock_resident: 'Invalid resident for TownBlock %s. Skipped setting resident for TownBlock...'
flatfile_err_loading_group_list_at_line: 'Error loading Group List at %s, in towny/data/groups.txt'
flatfile_err_loading_world_list_at_line: 'Error loading World list at %s, in towny/data/worlds.txt'
flatfile_err_nation_could_not_load_capital_disband: 'The nation %s could not load a capital city and is being disbanded.'
flatfile_err_reading_nation_file_at_line: 'Loading Error: Exception while reading nation file %s at line %s, in towny/data/nations/%s.txt'
flatfile_err_reading_outlaw_of_town_duplicate: 'Loading Error: Exception while reading an outlaw of town file %s.txt. The outlaw %s is duplicated! Skipping adding duplicate...'
flatfile_err_reading_outlaw_of_town_not_exist: 'Loading Error: Exception while reading an outlaw of town file %s.txt. The outlaw %s does not exist! Removing from list...'
flatfile_err_reading_resident_at_line: 'Loading Error: Exception while reading resident file %s at line: %s, in towny/data/residents/%s.txt'
flatfile_err_reading_town_file_at_line: 'Loading Error: Exception while reading town file %s at line: %s, in towny/data/towns/%s.txt'
flatfile_err_resident_tried_load_invalid_town: 'Loading Error: %s tried to load the town %s which is invalid. Removing town from the resident.'
flatfile_err_town_homeblock_not_exist: '[Warning] %s does not have a HomeBlock.'
flatfile_err_townblock_file_contains_unregistered_town_delete: 'TownBlock file contains unregistered Town: %s, deleting %s'
flatfile_err_townblock_file_missing_town_delete: 'TownBlock file missing Town, deleting %s'
flatfile_err_townblock_file_unknown_err: 'TownBlock file contains unknown error, deleting %s.'
```

____
#### Relevant Towny Issue ticket:

None - this was a personal experiment.

____
- [x] I have tested this pull request for defects on a server. No errors at startup.

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Looks good, the only downside I can see from this is someone using a translated version of these strings ends up needing support and I cannot read the debug/error messaging.

**Comment by GNosii** [comment]
This is an small suggestion but as an "solution" to the downside mentioned by @LlmDl, the translated message should be accompanied by the string name itself, something like this:

`TownBlock file contains unknown error, deleting London. (flatfile_err_townblock_file_unknown_err)`

**Comment by LlmDl** [comment]
Needs a rebase to solve the conflict in the changelog.

**Comment by TheFlagCourier** [comment]
@LlmDl I'll check out the conflicts when I get back to town this afternoon.

@GNosii Not a bad idea.

**Pull request merged**
