### PR TITLE
API: Add PlotPreClaimEvent and PlotClaimEvent

### PR DESCRIPTION
**Pull request by Warriorrrr**
#### Description: 

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — CHANGES_REQUESTED** [review]
I did some looking into where TownBlock#setResident() is called from, while this is being called when someone claimed a plot, it is also being called whenever:
- someone is evicted, 
- an admin swaps a plot to another town, 
- a town goes to ruin and all players lose their plots,
- a player leaves town and loses their non-embassy plots,
- `/plot unclaim`ing
- `/plot claim`'
- a player cannot pay daily taxes and failure to pay plot taxes 

The previous event, PlotChangeOwnerEvent is more accurate as this Event would be firing more for an unclaim than a claim.

I think a solution would be to add 2 more Unclaim events, whether TownBlock#setResident() is being sent null could determine when it fires the Unclaim events.

It might also be prudent to have the non-payment-for-plot-taxes not be something which can be cancelled, but that might be bad API.

**Comment by JaHollYT** [comment]
Maybee a PlotPreChangeOwnerEvent is a good idea - so that you can cancel PlotChangeOwnerEvent

**Comment by JaHollYT** [comment]
@Warriorrrr @LlmDl Are there any News about this pull-request?
I love the idea and have use cases :)

**Comment by LlmDl** [comment]
@JaHollYT There's some requested changes on this PR, which I have [a secondary PR](https://github.com/TownyAdvanced/Towny/pull/5439) for, which just needs approval.

**Review by LlmDl — APPROVED** [review]

**Pull request merged**
