### PR TITLE
Add embassies in resident status

### PR DESCRIPTION
**Pull request by SeruhioX**
Some of my users asked me that they could see in which cities they have embassies executing /p

https://i.gyazo.com/a8a7532f27eca32d9f99cfd0b92f8428.png

### CODE REVIEW

**Comment by LlmDl** [comment]
This is a pretty cool idea.

**Comment by LlmDl** [comment]
If you want to, can you switch the language files to remove the part about Added in .51, because 0.94.0.4 isn't out yet, .50 is still in effect.

**Comment by SeruhioX** [comment]
> If you want to, can you switch the language files to remove the part about Added in .51, because 0.94.0.4 isn't out yet, .50 is still in effect.

Sure ;)

**Comment by LlmDl** [comment]
Is this ready to merge now?

**Comment by amnrmain** [comment]
Yes, I would like it to be in version 1.13.2, I am testing it before the subsequent changes of 1.14.x (0.94.0.0), but I have copied the methods and compiled correctly, so it should work the same as in my local.

**Comment by SeruhioX** [comment]
Yes, I would like it to be in version 1.13.2, I am testing it before the subsequent changes of 1.14.x (0.94.0.0), but I have copied the methods and compiled correctly, so it should work the same as in my local.

**Comment by LlmDl** [comment]
Ok, I'll get this merged today hopefully. It'll go in before 0.94.0.4 is out for sure.

**Pull request merged**
