### PR TITLE
Flagwar Feature: Option to disable the capture of a defender's TownBlocks

### PR DESCRIPTION
**Pull request by TheFlagCourier**
Closes ticket #3514

Adds language file entry to broadcast this to the attacking and defending towns.

See ChangeLog for full commit description.

(Also fixes spelling of WAR_ENEMY_FLAG)

### CODE REVIEW

**Comment by TheFlagCourier** [comment]
Yeah the only reason I didn't do that, it's because I had no idea when this would have been merged. I can push a commit later to bump the version, but I'm away from my computer at the moment.

**Comment by LlmDl** [comment]
> Yeah the only reason I didn't do that, it's because I had no idea when this would have been merged. I can push a commit later to bump the version, but I'm away from my computer at the moment.

If you don't get to it first I'll do it post-merge.

**Comment by TheFlagCourier** [comment]
Don't merge - forgot to actually bump the dang versions...

**Comment by DalBrar** [comment]
Thank TheFlagCourier!! <3

**Pull request merged**
