### PR TITLE
Args cut remove

### PR DESCRIPTION
**Pull request by Lemar98**
#### Description: 
While testing the TownyAddon CommandsAPI, I noticed that the command handler for some reason does not return the name of the city to me when I enter /townyadmin town <town> my_custom_cmd, but only "my_custom_cmd". I think this is wrong, so I decided to make a PR regarding this situation.

It seems to me that cutting the argument in the #execute method is not a good idea, since the arguments are also cut before calling this method

Also, I do not rule out that this PR may break some plugins if they use the TownyAddonCommandAPI, since an extra argument may be added to some processed commands, which can lead to incorrect execution of logic.

- [x] I have tested this pull request for defects on a my local server with one custom argument.

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
The code you've changed will alter all of the addon commands. Any existing plugin will have to account for the new arg preceding what was originally being passed.

If there is an issue in TownyAdminCommand it should be addressed there locally. I'll look into it later.

**Comment by Lemar98** [comment]
I will wait for your solution.

**Comment by LlmDl** [comment]
Your custom command is using the `/ta town TOWNNAME customcommand` right?

**Comment by Lemar98** [comment]
Yes

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commit/0a2d88db5019f3c2ffafebe9ba8fbe2d12bd3203 Should take care of this and give us an avenue for if/when new AddonCommands require a object.

**Pull request closed without merging**
