### PR TITLE
Added a cancellable event for removal of mobs on spawn

### PR DESCRIPTION
**Pull request by lucasboss45**
#### Description: 
This pull request adds a cancellable event to the removal of mobs on spawn

____
#### New Nodes/Commands/ConfigOptions: 
N/A

____
#### Relevant Towny Issue ticket:
N/A

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
I'm wondering if this needs to be a separate event from the MobRemovalEvent that's fired when mobs wander into non-Mob land.

I'm guessing this is to make it so that mobs can wander in to town but not spawn inside towns?

**Comment by lucasboss45** [comment]
> I'm wondering if this needs to be a separate event from the MobRemovalEvent that's fired when mobs wander into non-Mob land.
> 
> I'm guessing this is to make it so that mobs can wander in to town but not spawn inside towns?

This actually because I need to allow certain mobs to spawn in non mob land on very specific senarios, I'm already using the MobRemovalEvent but that doesn't cover mobs spawning directly inside the land

**Comment by LlmDl** [comment]
> > I'm wondering if this needs to be a separate event from the MobRemovalEvent that's fired when mobs wander into non-Mob land.
> > I'm guessing this is to make it so that mobs can wander in to town but not spawn inside towns?
> 
> This actually because I need to allow certain mobs to spawn in non mob land on very specific senarios, I'm already using the MobRemovalEvent but that doesn't cover mobs spawning directly inside the land

Sounds good, on first read through I didn't see any issues here. I'll take another look later on/probably see if any other team members want to chime in.

**Comment by LlmDl** [comment]
One thing that will probably change is we'll need the event moved into a mobs sub-package, we're going to be moving the events over to sub-packages in the future so new ones will go into their own package.

**Comment by LlmDl** [comment]
I attempted to fix the package but it looks like I am not able to commit to your repo.

**Review by LlmDl — CHANGES_REQUESTED** [review]
The new event will need to move into a new mob package within the event package.

**Comment by lucasboss45** [comment]
I believe I've made the required changes

**Comment by LlmDl** [comment]
> The new event will need to move into a new mob package within the event package.

I'll need you to move the MobRemovalEvent back to where it was, we haven't quite decided how to handle the deprecation of the old events, so it is only new events which are being put in sub-packages at the moment.

**Review by LlmDl — APPROVED** [review]

**Pull request merged**
