### PR TITLE
Fix lists not being cleared (memory leak)

### PR DESCRIPTION
**Pull request by Agaloth**
#### Description: 
This would cause a memory leak issue. Basically the lists were never being cleared and after the server has been running for a day it would end up having lag issues and freezes. Here is a preview of the heap dump:
image

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by Agaloth** [comment]
Forgot a part of the code but basically, I removed CompletableFuture since it's not safe at all and this is much better and makes the code work as intended and shouldn't add any performance issues.

**Review by Warriorrrr — CHANGES_REQUESTED** [review]
I don't think this is very likely to have any effect (nor do I think there's even a memory leak here since we're not holding onto any references), everything that happens inside the future is safe.

**Comment by LlmDl** [comment]
There are unneeded changes to the diff made which would have to be removed. Might be helpful to see more about your system in case this is something that isn't happening to other servers.

**Comment by Agaloth** [comment]
> There are unneeded changes to the diff made which would have to be removed. Might be helpful to see more about your system in case this is something that isn't happening to other servers.

What type of information should I provide? :)

**Comment by LlmDl** [comment]
A server startup is usually included with bug reports, also it would be useful to see the java args you use to start your server.

**Pull request closed without merging**
