### PR TITLE
Adds Jail Events

### PR DESCRIPTION
**Pull request by Kovalskki**
#### Description: 
I need these events for my plugin.

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — COMMENTED** [review]
Looks fairly good. Will you be testing this?

**Comment by Kovalskki** [comment]
> Looks fairly good. Will you be testing this?

I'm trying now

**Comment by Kovalskki** [comment]
> Looks fairly good. Will you be testing this?

Worked without error

Ekran Alıntısı

**Comment by Kovalskki** [comment]
Hmmm getJailTown() method returned null :(

**Comment by Kovalskki** [comment]
I also tested the things I added. They work smoothly.

**Review by LlmDl — APPROVED** [review]

**Comment by LlmDl** [comment]
Thanks for the PR. I'll probably end up fleshing the events out a bit when the jail system is re-done next year.

**Comment by LlmDl** [comment]
In an attempt to add some convenience methods to your branch I have somehow borked it good. If I was able to forcepush to your repo I can get the commits back in place.

**Pull request closed without merging**
