### PR TITLE
Maven: Add IdConverter's IdMappings to dependencies, remove from tree

### PR DESCRIPTION
**Pull request by TheFlagCourier**
Moves away from including someone else's code in the repository. They provide a nice way to include it using Maven, so this should help. Added benefit is it can be updated by changing the version number.

(Pom.xml converted to CRLF?)

### CODE REVIEW

**Comment by LlmDl** [comment]
Did you test using this in the revert on unclaim? If I recall I had to make some modifications to the original class, because it could sometimes return null and because it had some of the new names wrong (Grass blocks was one of them.)

**Comment by LlmDl** [comment]
To test you'll need some pre-1.13 townblock plot-snapshots to revert from.

**Comment by TheFlagCourier** [comment]
Will do some testing when I get off work. If there are any necessary changes to make, I can always pull the old file and run a diff against theirs to see what needs done.

**Comment by TheFlagCourier** [comment]
Well... This _is_ interesting... I had thought it'd be closer to a 1:1 conversion.

 Looks like multiple blocks changed their mapped IDs since the last time this file was touched.
Upper-slabs don't exist upstream, either - so we have nine extra lines on our copy. (Perhaps a change between 1.12/13 and 1.14?)

image

Going to still test and see how it turns out. If modifications are needed, I'll see about working on that.

**Comment by TheFlagCourier** [comment]
I have not had the time to get around to this, and I definitely need to take a closer inspection on its integration. Closing and putting on the back burner for now.

**Pull request closed without merging**
