### PR TITLE
Fix switch and item use being triggered on left-click

### PR DESCRIPTION
**Pull request by devPesto**
#### Description: 

See issue linked below
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

Fix for #6494 

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — COMMENTED** [review]
I'd like to know that all of these tests still work:
```java
				Material clickedMat = clickedBlock.getType();
				/*
				 * Test stripping logs, scraping copper blocks, dye-able signs,
				 * glass bottles, flint&steel on TNT and shears on beehomes
				 * 
				 * Treat interaction as a Destroy test.
				 */
				if ((ItemLists.AXES.contains(item) && (ItemLists.UNSTRIPPED_WOOD.contains(clickedMat) || ItemLists.WAXED_BLOCKS.contains(clickedMat) || ItemLists.WEATHERABLE_BLOCKS.contains(clickedMat))) ||
					(ItemLists.DYES.contains(item) && Tag.SIGNS.isTagged(clickedMat)) ||
					(item == Material.FLINT_AND_STEEL && clickedMat == Material.TNT) ||
					((item == Material.GLASS_BOTTLE || item == Material.SHEARS) && (clickedMat == Material.BEE_NEST || clickedMat == Material.BEEHIVE || clickedMat == Material.PUMPKIN))) { 

					event.setCancelled(!TownyActionEventExecutor.canDestroy(player, loc, clickedMat));
				}

				/*
				 * Test bonemeal usage. Treat interaction as a Build test.
				 */
				if (item == Material.BONE_MEAL) 
					event.setCancelled(!TownyActionEventExecutor.canBuild(player, loc, item));
				
				/*
				 * Test putting candles on cakes. Treat interaction as a Build test.
				 */
				if (ItemLists.CANDLES.contains(item) && clickedMat == Material.CAKE) 
					event.setCancelled(!TownyActionEventExecutor.canBuild(player, loc, item));
				
				/*
				 * Test wax usage. Treat interaction as a Build test.
				 */
				if (item == Material.HONEYCOMB && ItemLists.WEATHERABLE_BLOCKS.contains(clickedMat))
					event.setCancelled(!TownyActionEventExecutor.canBuild(player, loc, item));

				/*
				 * Test if we're about to spawn either entity. Uses build test.
				 */
				if (item == Material.ARMOR_STAND || item == Material.END_CRYSTAL) 
					event.setCancelled(!TownyActionEventExecutor.canBuild(player, clickedBlock.getRelative(event.getBlockFace()).getLocation(), item));

				/*
				 * Test if we're putting a book into a BookContainer.
				 */
				if (ItemLists.PLACEABLE_BOOKS.contains(item) && ItemLists.BOOK_CONTAINERS.contains(clickedMat))
					event.setCancelled(!TownyActionEventExecutor.canBuild(player, loc, item));

				/*
				 * Catches hoes taking dirt from Rooted Dirt blocks.
				 */
				if (clickedMat.name().equals("ROOTED_DIRT") && item.name().toLowerCase().contains("_hoe"))
					event.setCancelled(!TownyActionEventExecutor.canDestroy(player, clickedBlock));

```

Some are obviously right clicks, some I wonder about left-clicking still working though, like armor stands and endcrystals.

**Comment by devPesto** [comment]
I've tested the checks you requested and all seem to work as intended

**Comment by LlmDl** [comment]
> I've tested the checks you requested and all seem to work as intended

I asked on the discord but it may as well go here for the record: Are armor_stands and end_crystals still protected from left clicking?

**Comment by devPesto** [comment]
> > I've tested the checks you requested and all seem to work as intended
> 
> I asked on the discord but it may as well go here for the record: Are armor_stands and end_crystals still protected from left clicking?

Yes, both are protected by destroy perms. If switch perms are enabled and destroy perms are disabled, both are protected as intended.

**Pull request merged**
