### PR TITLE
Extract SiegeWar code from TownyFormatter

### PR DESCRIPTION
**Pull request by docwhomc**
#### Description: 

Move SiegeWar code in `TownyFormatter` into its own class, `SiegeWarFormatter`.
____
#### New Nodes/Commands/ConfigOptions: 

None

____
#### Relevant Towny Issue ticket:

None

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Conflicts on this one. If you could start using the Towny repo instead of your fork, I'd be able to resolve this and other things that can come up (without setting up your fork as a remote and you allowing me to push to it.)

**Review by LlmDl — CHANGES_REQUESTED** [review]
Conflicts on this one. If you could start using the Towny repo instead of your fork, I'd be able to resolve this and other things that can come up (without setting up your fork as a remote and you allowing me to push to it.)

**Comment by docwhomc** [comment]
> Conflicts on this one. If you could start using the Towny repo instead of your fork, I'd be able to resolve this and other things that can come up (without setting up your fork as a remote and you allowing me to push to it.)

I've tried, but you didn't give me the necessary perms to push to TownyAdvanced/Towny branches, even if I was the one who created them.  We discussed it last night, remember?

**Comment by LlmDl** [comment]
> > Conflicts on this one. If you could start using the Towny repo instead of your fork, I'd be able to resolve this and other things that can come up (without setting up your fork as a remote and you allowing me to push to it.)
> 
> I've tried, but you didn't give me the necessary perms to push to TownyAdvanced/Towny branches, even if I was the one who created them. We discussed it last night, remember?

Fixed that last night, might not have said I did.

**Comment by docwhomc** [comment]
> > > Conflicts on this one. If you could start using the Towny repo instead of your fork, I'd be able to resolve this and other things that can come up (without setting up your fork as a remote and you allowing me to push to it.)
> > 
> > 
> > I've tried, but you didn't give me the necessary perms to push to TownyAdvanced/Towny branches, even if I was the one who created them. We discussed it last night, remember?
> 
> Fixed that last night, might not have said I did.

That wasn't until after I had to make the new branch for the PR.

Conflicts resolved.

**Pull request merged**
