### PR TITLE
Let admins bypass nation capital resident limits

### PR DESCRIPTION
**Pull request by Gamer153**
#### Description:
Admins using `/ta nation <nation> set <capital|king>` now bypass checks for resident limits for the new and old capital. This makes it easier to transfer the nation to a new king without impacting the old capital or its residents.

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — CHANGES_REQUESTED** [review]
This looks good but I wonder if admins should be notified they're about to override the server's config's ruleset before allowing it.

This could be done by adding a Confirmation that would only be presented when admin == true.

**Comment by LlmDl** [comment]
Looks good to me, has the new confirmation stuff been tested?

**Comment by Gamer153** [comment]
Yes, it all seems to work.

**Comment by LlmDl** [comment]
I'm afraid I broke the en-US.yml on my end of things, can you rebase your file off of master?

**Comment by LlmDl** [comment]
During the rebase process, it managed to only push the rebase and not your commits (I still have them locally,) and my internet connection is bugging out right now so I haven't been able to push them.

**Pull request closed without merging**
