### PR TITLE
Extract SiegeWar code from TownyUniverse

### PR DESCRIPTION
**Pull request by docwhomc**
#### Description: 

Move SiegeWar code from `TownyUniverse` into its own class, `SiegeWarUniverse`.

____
#### New Nodes/Commands/ConfigOptions: 

None

____
#### Relevant Towny Issue ticket:

None

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
Still not sure if this should be something called a "universe" and not just a SiegeMap.

The actual use case starts to look like:
```java
    SiegeMap siegeMap = SiegeMap.getInstance().getSiegeMap();
    siegeMap.remove(oldSiegeName.toLowerCase());
    siegeMap.put(newSiegeName.toLowerCase(), siege);					    
```
instead of 
```java
    SiegeWarUniverse siegeWarUniverse = SiegeWarUniverse.getInstance();
    siegeWarUniverse.getSiegesMap().remove(oldSiegeName.toLowerCase());
    siegeWarUniverse.getSiegesMap().put(newSiegeName.toLowerCase(), siege);
```

There really aren't any other things being stored on it. No nations or towns with active sieges or anything.

**Comment by docwhomc** [comment]
> Still not sure if this should be something called a "universe" and not just a SiegeMap.
> 
> The actual use case starts to look like:
> 
> ```java
>     SiegeMap siegeMap = SiegeMap.getInstance().getSiegeMap();
>     siegeMap.remove(oldSiegeName.toLowerCase());
>     siegeMap.put(newSiegeName.toLowerCase(), siege);					    
> ```
> 
> instead of
> 
> ```java
>     SiegeWarUniverse siegeWarUniverse = SiegeWarUniverse.getInstance();
>     siegeWarUniverse.getSiegesMap().remove(oldSiegeName.toLowerCase());
>     siegeWarUniverse.getSiegesMap().put(newSiegeName.toLowerCase(), siege);
> ```
> 
> There really aren't any other things being stored on it. No nations or towns with active sieges or anything.

There is the `getPlayersInBannerControlSessions()`.  And this might be a good place to migrate the data currently tacked onto nations and towns if we don't want to add it as metadata.

**Comment by LlmDl** [comment]
> > Still not sure if this should be something called a "universe" and not just a SiegeMap.
> > The actual use case starts to look like:
> > ```java
> >     SiegeMap siegeMap = SiegeMap.getInstance().getSiegeMap();
> >     siegeMap.remove(oldSiegeName.toLowerCase());
> >     siegeMap.put(newSiegeName.toLowerCase(), siege);					    
> > ```
> > 
> > 
> > instead of
> > ```java
> >     SiegeWarUniverse siegeWarUniverse = SiegeWarUniverse.getInstance();
> >     siegeWarUniverse.getSiegesMap().remove(oldSiegeName.toLowerCase());
> >     siegeWarUniverse.getSiegesMap().put(newSiegeName.toLowerCase(), siege);
> > ```
> > 
> > 
> > There really aren't any other things being stored on it. No nations or towns with active sieges or anything.
> 
> There is the `getPlayersInBannerControlSessions()`. And this might be a good place to migrate the data currently tacked onto nations and towns if we don't want to add it as metadata.

In order to eventually get things onto the status screens those things will have to end up being metadata.

**Review by LlmDl — CHANGES_REQUESTED** [review]
TownyDatabaseHandler and SiegeWarDynmapUtil both got fully formatted.

**Pull request closed without merging**
