### PR TITLE
Rewrite DB and add UUID support

### PR DESCRIPTION
**Pull request by suneettipirneni**
#### Description: 

More Detailed description coming soon(TM)...

Latest Build: 
[Towny-0.96.2.3.jar.zip](https://github.com/TownyAdvanced/Towny/files/4915586/Towny-0.96.2.3.jar.zip)
- Fixed Town Ranks Not loading.

____
- [ ] I have tested this pull request for defects on a server.

### CODE REVIEW

**Comment by suneettipirneni** [comment]
Note UUID for residents is currently randomly generated, this will be rectified in a later build

**Comment by silverwolfg11** [comment]
This is more for myself than anything just so I remember what needs to be done.

TODO:
- [ ] Convert all townyobject collections to use thread-safe collections (create serializers for each thread-safe collection)
- [ ] Work on migrating economy to save as `object_UUID` instead of name based.
- [ ] Make sure townyobject permissions save properly
- [ ] Test whether plot groups even save / load.
- [ ] Test that metadata save / loads properly for townyobjects
- [ ] Test that nation allies / enemies save / load properly.
- [ ] Test that regen / plot snapshot queue saves and loads properly.
- [ ] Test that resident friends are loading / saving properly. 
- [ ] Implement missing methods for SQL database handler.
- [ ] Test migration from old database to new database.

**Comment by suneettipirneni** [comment]
The towny objects shouldn't be using CopyOnWrite lists. When I said that in discord I was assuming you were talking about capturing the list in a separate external collection. Regardless if you want a threadsafe collection on the object itself synchronized collections are a much better choice.

**Comment by silverwolfg11** [comment]
Like you mentioned in discord, the synchronized collections do not provide a thread-safe iterator (not w/o manual synchronization anyway). Since that's really the only thread-safe thing the save-thread needs, I went w/ the COW list since it has the thread-safe iterator.

I don't quite see why the towny objects can't have COW list? To reduce performance cost, I only changed the non-transient collections to concurrent objects.

The other alternative I considered was caching which fields have collections and then a shallow-clone of the collection would be produced on the main thread and stored in the immutable save-queue object. 
However, the reason I went w/ the COW lists was well they were just easier to implement, they allow the save-method to be safely called on any thread, and there is absolutely minimal performance cost on the save method since it only adds the object to the save map.

**Comment by suneettipirneni** [comment]
> Like you mentioned in discord, the synchronized collections do not provide a thread-safe iterator (not w/o manual synchronization anyway). Since that's really the only thread-safe thing the save-thread needs, I went w/ the COW list since it has the thread-safe iterator.

Manually synchronizing is not something that's hard especially when you're only dealing with a producer and consumer thread. Whenever you read the collection in the background thread you need to just synchronize on it in a block. 

> I don't quite see why the towny objects can't have COW list? To reduce performance cost, I only changed the non-transient collections to concurrent objects.

First off, using COW's are not going to be just a little less performant but a lot less performant. COW lists aren't meant for objects that receive frequent writes. As the name suggests, every time you add/remove something to the array it reallocates it's *entire* backing array. Imagine adding a townblock to a town that already owns 1000's of townblocks, everytime a townblock is added or removed that entire array is reconstructed. Also even for some simple read operations like accessing its iterator, it makes another copy of itself to create a *snapshot* iterator. As a result, using a COW is *much* slower than using a synchronized collection which only locks when saving, and all main thread operations are just as fast as using a regular collection. With a COW both main thread operations and background thread operations are much slower.

**Comment by suneettipirneni** [comment]
This is being closed as the majority of this code is written by me as well as my additional input and feedback. As I cannot have any form of contact with the repo owner this will not work. I am formally rescinding the modification of my work in this branch and closing this PR.

**Comment by Momshroom** [comment]
:(

**Comment by suneettipirneni** [comment]
Ignore my previous comments, this branch is free for modification.

**Comment by LlmDl** [comment]
The team has decided this branch will not be necessary.

**Pull request closed without merging**
