### PR TITLE
Add towny.receives-plot-notifications permission

### PR DESCRIPTION
**Pull request by invpt**
#### Description: 

Adds a ~~`towny.notify`~~ `towny.receives-plot-notifications` permission that must be present in order for players to be notified when they move between plots.

##### Unresolved concerns
- ~~Is `towny.notify` the best name for the permission? Is there a more descriptive name?~~
  - Renamed to `towny.receives-plot-notifications`
- ~~As-is, servers that upgrade to a version with this change would have to manually add `towny.notify` to `townyperms.yml` to restore notification functionality as it was before the update. I'm not sure of the best way to get around this - as far as I can tell, there is no current precedent for migrating `townyperms.yml`.~~
  - Resolved by making the permission default in `plugin.yml`
____
#### New Nodes/Commands/ConfigOptions: 

New permission node: `towny.receives-plot-notifications`.

____
#### Relevant Towny Issue ticket:

#6907

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by LlmDl** [comment]
It's a lot simpler to add the new permission node (which ought to be more descriptive,) as a node handed out by default in the plugin.yml. Then LP can be used to set it to false, instead of it having to be granted.

**Comment by invpt** [comment]
Ah, I forgot you can add default perms in plugin.yml. Sounds like the right solution.

**Review by LlmDl — CHANGES_REQUESTED** [review]
I would suggest changing the permission node to `towny.receives-plot-notifications` which is more in-tune with the already used lingo.

**Review by LlmDl — CHANGES_REQUESTED** [review]
Looks good with a couple of small suggestions

**Review by LlmDl — APPROVED** [review]

**Comment by LlmDl** [comment]
Thanks for taking care of all of that.

**Pull request merged**
