### PR TITLE
Alter /t buytown logic to prevent total loss of money

### PR DESCRIPTION
**Pull request by Fruitloopins**
#### Description: 

This PR should fix an error that occurs when players attempt to buy a town when they do not have enough money under certain server configurations

An error will say they don't have enough to pay but it will still take all the money they currently have on them. This changes the logic to first check if they have the required amount of money and then it withdraws it after rather than attempt to take it out anyways and error if it doesn't completely work

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — APPROVED** [review]

**Comment by LlmDl** [comment]
This is fine, but .withdraw() doesn't take money if its not allowed to take all of the money. The economy plugin is probably at fault here.

**Comment by Fruitloopins** [comment]
yeah i wasn't exactly sure what it was but figured this should just solve it

**Comment by LlmDl** [comment]
> yeah i wasn't exactly sure what it was but figured this should just solve it

What economy plugin are you using when you see this behaviour?

**Comment by Fruitloopins** [comment]
pretty sure we are using a custom one made by warrior

**Comment by Fruitloopins** [comment]
but he didn't respond to me asking about this bug

**Pull request closed without merging**
