### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by OskyEdz**
#### Description: 
Added a lot of new entries to the swedish langugae file. It is a long way to complete, but others could easily use this as a base. I'll also accept help from my fellow sweeds!

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by OskyEdz** [comment]
I'll see if I'm able to connect Github with that one.

**Comment by LlmDl** [comment]
Changes to the .gitignore and english.yml files will have to be undone.

**Comment by OskyEdz** [comment]
Yeah, I tried to undo. Git is not like that.

**Comment by LlmDl** [comment]
Sorted it out on my end.

**Pull request merged**
