### PR TITLE
Provided the full legal text for CC-BY-NC-ND 3.0 Unported

### PR DESCRIPTION
**Pull request by MilesBHuff**
#### Description: 
Projects should ideally provide the full legal text of the license they are using.
I have copied the appropriate plaintext legal code for CC-BY-NC-ND 3.0 Unported from https://creativecommons.org/licenses/by-nc-nd/3.0/legalcode.txt.
This will also hopefully get GitHub to correctly display the license in the sidebar.

*By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.*

### CODE REVIEW

**Comment by LlmDl** [comment]
Have you seen anything to suggest it would make github recognize the license? I might end up making this change myself, a fair bit of the formatting of the license has been lost, including some of the sub-headings ("a.", "b.", "c.", etc.) which are referenced directly in the license itself (making the license.txt somewhat incomplete/unreadable.)

**Comment by MilesBHuff** [comment]
@LlmDl 
> Have you seen anything to suggest it would make github recognize the license?

GitHub supports CC-BY-SA, but I'm not sure about CC-BY-NC-ND 3.  Worst-case scenario, it will just continue showing "View License".  Nevertheless, it's still a good idea to include the full text.

> I might end up making this change myself, a fair bit of the formatting of the license has been lost

By all means!  I just copied the official plaintext version, from creativecommons.org.

**Comment by GNosii** [comment]
Hello, think this may help: GitHub uses Licensee ([Repo](https://github.com/licensee/licensee)) to detect repository licenses, which describes how licenses are detected over [here](https://licensee.github.io/licensee/what-we-look-at/).

**Comment by LlmDl** [comment]
> Hello, think this may help: GitHub uses Licensee ([Repo](https://github.com/licensee/licensee)) to detect repository licenses, which describes how licenses are detected over [here](https://licensee.github.io/licensee/what-we-look-at/).

I was fairly certain that Github wasn't able to recognize the license we use. I don't think there's any way for it to show on the main GH page.

**Comment by MilesBHuff** [comment]
> Github wasn't able to recognize the license we use.

Yeah, it seems the only Creative Commons licenses currently supported are CC-BY-4, CC-BY-SA-4, and CC0.
https://github.com/licensee/licensee/tree/master/vendor/license-list-XML/src

> I don't think there's any way for it to show on the main GH page.

I think it would show if someone were to add CC-BY-NC-ND-3 to the repo at the above link.
Adding the full text of the license now will have it show in the future if anyone ever does that.

**Pull request closed without merging**
